AutoWebApp/AutoWebApp/Entities/Auto.cs
using System;
using System.Collections.Generic;

namespace AutoWebApp.Entities;

public partial class Auto
{
    public Guid Autoid { get; set; }

    public string Modell { get; set; } = null!;

    public string Marke { get; set; } = null!;

    public DateOnly? Baujahr { get; set; }

    public int? Preis { get; set; }

    public Guid? Kategorienid { get; set; }
}

AutoWebApp/AutoWebApp/Entities/Autokategorie.cs
using System;
using System.Collections.Generic;

namespace AutoWebApp.Entities;

public partial class Autokategorie
{
    public Guid Kategorienid { get; set; }

    public string Bezeichnung { get; set; } = null!;
}

AutoWebApp/AutoWebApp/Entities/Kunde.cs
using System;
using System.Collections.Generic;

namespace AutoWebApp.Entities;

public partial class Kunde
{
    public Guid Kundenid { get; set; }

    public string Vorname { get; set; } = null!;

    public string Nachname { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string Wohnort { get; set; } = null!;

    public string Straße { get; set; } = null!;

    public int? Postleitzahl { get; set; }
}

AutoWebApp/AutoWebApp/Entities/Verkauf.cs
using System;
using System.Collections.Generic;

namespace AutoWebApp.Entities;

public partial class Verkauf
{
    public Guid Verkaufsid { get; set; }

    public DateOnly? Verkaufsdatum { get; set; }

    public Guid? Autoid { get; set; }

    public Guid? Kundenid { get; set; }
}

AutoWebApp/AutoWebApp/Models/ErrorViewModel.cs
namespace AutoWebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AutoWebApp/AutoWebApp/Controllers/AutoController.cs
using AutoWebApp.Context;
using AutoWebApp.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoWebApp.Controllers;

public class AutoController : Controller
{
    // GET
    public IActionResult Index()
    {
        //Repository ertsellen
        MyDbContext dbctx = new MyDbContext();
        //Alle Burger Items auslesen
        List<Auto> auto = dbctx.Auto.ToList();
        //Der View übergeben
        return View(auto);
    }

    [HttpPost]
    public IActionResult SaveAuto(Auto auto)
    {
        MyDbContext dbctx = new MyDbContext();
        dbctx.Auto.Add(auto);
        dbctx.SaveChanges();
        return RedirectToAction("Index");
    }
    
    public IActionResult UpdateAuto(Auto auto)
    {
        MyDbContext dbctx = new MyDbContext();
        dbctx.Auto.Update(auto);
        dbctx.SaveChanges();
        return RedirectToAction("Index");
    }
    public IActionResult New()
    {
        return View();
    }

    public IActionResult Edit(Guid id)
    {
        MyDbContext dbctx = new MyDbContext();
        Auto auto = dbctx.Auto.FirstOrDefault(a => a.Autoid == id);
        return View(auto);
    }
    
    public IActionResult Delete(Guid id)
    {
        MyDbContext dbctx = new MyDbContext();
        Auto autoToDelete = dbctx.Auto.FirstOrDefault(a => a.Autoid == id);
        dbctx.Auto.Remove(autoToDelete);
        dbctx.SaveChanges();
        return RedirectToAction("Index");
    }
}

AutoWebApp/AutoWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using AutoWebApp.Context;
using Microsoft.AspNetCore.Mvc;
using AutoWebApp.Models;

namespace AutoWebApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        MyDbContext dbctx = new MyDbContext();
        int AutoAnzahl = dbctx.Auto.Count();
        
        ViewData["TestData"] = AutoAnzahl.ToString();
        
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AutoWebApp/AutoWebApp/Views/Auto/Edit.cshtml
@model AutoWebApp.Entities.Auto

@{
    ViewData["Title"] = "Auto Editieren";
}

<h1>Edit Auto</h1>

<form action="/Auto/UpdateAuto" method="post">
    
    <input type="hidden" id="Autoid" name="Autoid" value="@(Model.Autoid)"/>
    
    <table>
        <tr>
            <td>
                Marke
            </td>
            <td>
                <input type="text" id="Marke" name="Marke" value="@(Model.Marke)"/>
            </td>
        </tr>
        <tr>
            <td>
                Modell
            </td>
            <td>
                <input type="text" id="Modell" name="Modell" value="@(Model.Modell)"/>
            </td>
        </tr>
        <tr>
            <td>
                Preis
            </td>
            <td>
                <input type="number" id="Preis" name="Preis" value="@(Model.Preis)"/>
            </td>
        </tr>
        <tr>
            <td>
                <a class="btn btn-danger" href="/Auto/">Cancel</a>
            </td>
            <td>
                <button type="submit" class="btn btn-success">Save</button>
            </td>
        </tr>
    </table>
</form>

AutoWebApp/AutoWebApp/Views/Auto/Index.cshtml
@model List<AutoWebApp.Entities.Auto>

@{
    ViewData["Title"] = "Auto Übersicht";
}

<h1>Autos</h1>

<a href="/Auto/New" class="btn btn-primary">New Auto</a>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Marke</th>
        <th>Modell</th>
        <th>Preis</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    
    @{
        foreach (var auto in Model)
        {
            <tr>
                <td>@(auto.Autoid)</td>
                <td>@(auto.Marke)</td>
                <td>@(auto.Modell)</td>
                <td>@(auto.Preis)</td>
                <td>
                    <a class="btn" href="/Auto/Edit?id=@(auto.Autoid)">✏️ Edit</a>
                    <a class="btn" href="/Auto/Delete?id=@(auto.Autoid)">❌ Delete</a>
                </td>
            </tr>
        }
    }
    
    </tbody>
</table>

AutoWebApp/AutoWebApp/Views/Auto/New.cshtml
@model List<AutoWebApp.Entities.Auto>

@{
    ViewData["Title"] = "Auto Erstellen";
}

<h1>New Auto</h1>

<form action="/Auto/SaveAuto" method="post">
    <table>
        <tr>
            <td>
                Marke
            </td>
            <td>
                <input type="text" id="Marke" name="Marke"/>
            </td>
        </tr>
        <tr>
            <td>
                Modell
            </td>
            <td>
                <input type="text" id="Modell" name="Modell"/>
            </td>
        </tr>
        <tr>
            <td>
                Preis
                </td>
            <td>
                <input type="number" id="Preis" name="Preis"/>
            </td>
        </tr>    
        <tr>
            <td>
                <a class="btn btn-danger" href="/Auto/">Cancel</a> 
            </td>
            <td>
                <button type="submit" class="btn btn-success">Save</button> 
            </td>
        </tr>
    </table>
</form>

AutoWebApp/AutoWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>AutoAnzahl: @(ViewData["TestData"])</h1>

AutoWebApp/AutoWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AutoWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AutoWebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoWebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Auto" asp-action="Index">Autos 🚗</a>
                                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - AutoWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>